### ISSUE TITLE
[Improvement] Update tests

### ISSUE THREAD

**Issue by lubird** [segmentio/analytics-php#132]
Update testing suite to use CircleCI, and ensure that each commit has the full suite of unit tests and end-to-end tests running.

**Tasks:**
- [x] Link repo to CircleCI
- [x] Remove old Travis link
- [x] Break down config.yml file into workable chunks
- [x] Ensure test suite is run across multiple support versions (5.3+, 7.x)
