### ISSUE TITLE
[Feature] Add limits to message, batch and memory usage

### ISSUE THREAD

**Issue by lubird** [segmentio/analytics-php#137]
The SDK needs to ensure it doesn’t use up too much memory/storage and should drop messages on the client after a maximum number of messages have been queued. Factors which impact this decision are:

1. Maximum size of a single message in a batch (32KB)
1. Maximum size of a batch (500KB)
1. 32MB limit to the internal queue

Should any limits be hit, emit an Error log event.

**Tasks:**
- [ ] Limit single message to 32KB
- [ ] Limit batch size to 500KB
- [ ] Limit total queue size to 32MB
